### ISSUE TITLE
Create the grabber arm ROS node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#1]
This task entails:

-Writing a ROS grabber arm node
    -Node must handle all cases
    -Read in ascii control commands/returns to and from the grabber and peripheral manager node
    -Create a test case node to "fake" systems for input from grabber and peripheral manager node and 
    test for correct function and output
    - Node must return conformation to peripheral manager of performed action

**Comment by batesandy123** [comment]
Removed as there is currently no grabber. Will reopen issue if this changes
