### ISSUE TITLE
Create the IMU ROS node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#10]
This task entails:

-Writing a ROS IMU node
-Node must handle all cases
-Read in ascii control commands/returns to and from the IMU and info manager node
-Create a test case node to "fake" systems for input from IMU and info manager node and
test for correct function and output
-Node must return conformation to peripheral manager of performed action
-Node must perform needed math and return relevant information extracted

**Comment by lymacasm** [comment]
This node has been created and tested using the IMU.
