### ISSUE TITLE
Create the motor info ROS node 

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#11]
This task entails:

-Writing a ROS motor info node
-Node must handle all cases
-Read in ascii control commands/returns to and from the motor info and info manager node
-Create a test case node to "fake" systems for input from motor info and info manager node and
test for correct function and output
-Node must return conformation to info manager of performed action
-Node must perform needed math and return relevant information extracted

**Comment by batesandy123** [comment]
Completed long ago. Was used in Robosub 2018
