### ISSUE TITLE
Set up a ROS node to on Jetson to publish to the GUI from the CSI camera

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#19]
As the title suggests, we now have the Jetson computer and now need to start doing work and setting systems up on the computer. The Jetson comes with a good camera that we can use at the very least for testing and debugging purposes. But the camera is a CSI camera and setup varies from regular usb cameras previously used. 

Task:
-write a ros node that opens the camera and publishes the information over a ros message (look at image transport messages).
-figure out drivers and camera issues involving CSI camera and write down any relevant information to working with the camera to be stored on the git wiki for other users.
-Have the GUI listen for the ROS message containing the video and display it in the GUI.

**Comment by asinha94** [comment]
Done in a previous commit by me. Used the https://github.com/ros-drivers/gscam package with DSTREAMER enables in the CMakeLists file. This can be done by adding `set(EXTRA_CMAKE_FLAGS "${EXTRA_CMAKE_FLAGS} -DGSTREAMER_VERSION_1_x=On")` to the top of the `CMakeLists.txt` file
