### ISSUE TITLE
Create the weight dropper ROS node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#2]
This task entails:

-Writing a ROS weight dropper node
-Node must handle all cases
-Read in ascii control commands/returns to and from the weight dropper and peripheral manager node
-Create a test case node to "fake" systems for input from weight dropper and peripheral manager node and test for correct function and output
- Node must return conformation to peripheral manager of performed action

**Comment by batesandy123** [comment]
Replaced by #54
