### ISSUE TITLE
Update the GUI for multiple camera input and a some sort of menu system to handle cases

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#20]
The GUI needs to be updated to handle and display multiple camera inputs. The submarine will have two camera inputs, along with the multiple inputs it would be beneficial to  be able to display raw footage and then the same input with detection markers for debugging purposes. The menu system needs to be able to handle switching between different sources and which window to display them in. 

Task:
 -Modify the GUI to have two windows for camera input.
-Create some sort of management menu/system to handle switching input to allow for switching between feeds.

**Comment by asinha94** [comment]
Done by @bates-andy123 in new gui
