### ISSUE TITLE
Set up webui to recievce key input for potential keyboard commands  

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#22]
Modify the GUI for keyboard input so that key commands can be sent from the a GUI terminal to the AUV. This is so we can perform testing on systems on demand with key control along with testing navigation with key control through GUI.

Task:
-Choose a key on the keyboard that you like and make an event for when the key is pressed.
-Have that key correspond to a command that will be sent over a ROS message to have something performed by the robot ex: fire the torpedo, navigation

**Comment by batesandy123** [comment]
Added #103
