### ISSUE TITLE
Modify the motor controller and motor controller controller code for new system

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#23]
The previous AUV from 2017(Nautilus) had two motor controllers for controlling the six motors present on the submarine and a controller for the two motor controllers. This year the submarine will have one motor controller and eight motors. The code needs to be moved to this repo and modified to handle the new system.

Task:
-Modify the old motor controller and motor controller controller code to only be one motor controller with an eight motor system.
-Move the modified code from the old repo to the current working repo for the 2018 AUV

**Comment by asinha94** [comment]
Done by @lymacasm and me across several commits
