### ISSUE TITLE
Create Functional testing framework

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#43]
***MIGRATED FROM REDHERRING REPO***

The framework should allow for

Simulating all kinds of hardware, whether it's USB devices or video cameras or batteries, etc
Should be isolated from ROS i.e setting up the virtual serial devices happens independently of the C++ setup
Serial ports should be programmed/configured into ROS by the framwork

**Comment by asinha94** [comment]
too much effort for precisely zero benefit
