### ISSUE TITLE
Create the hydrophone ROS node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#5]
This task entails:

-Writing a ROS hydrophone node
-Node must handle all cases
-Read in ascii control commands/returns to and from the hydrophone and peripheral manager node
-Create a test case node to "fake" systems for input from hydrophone and peripheral manager node and
test for correct function and output
-Node must return conformation to peripheral manager of performed action
-Node must perform needed math and return relevant information extracted

**Comment by batesandy123** [comment]
Worked great in at the Robosub 2018. Further things like constantly sampling will be implemented in hardware
