### ISSUE TITLE
Place this node in the to-be-created peripherals package. Similar to #124 create a basic node which just publishes any data it gets from the hydrophones and create a service call for any other functionality that the hydrophones has

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#52]
***MIGRATED FROM REDHERRING REPO***

Place this node in the to-be-created peripherals package. Similar to #124 create a basic node which just publishes any data it gets from the hydrophones and create a service call for any other functionality that the hydrophones has

**Comment by asinha94** [comment]
new architecture so not relavent anymore
