### ISSUE TITLE
Create the IMU node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#53]
***MIGRATED FROM REDHERRING REPO***

Place this node into the peripherals package. Follow #124 and create a basic node which just publishes everything it gets. Do some testing as well to make sure the errors dont get too crazy

**Comment by asinha94** [comment]
Also update the serial manager to figure out the best way to identify it

**Comment by asinha94** [comment]
Use old Java code as a base to write the new ROS code. The serial interface is slightly tricky

**Comment by batesandy123** [comment]
I tested out the serial connection to check that IMU does indeed work. I have uploaded my python code which shows how I read the temperature. The Java code is the old team code and is very useful for understanding what did in a macro sense. 

[IMU.zip](https://github.com/uvic-auvic/polaris/files/2019765/IMU.zip)

**Comment by asinha94** [comment]
Added skeleton ROS code in #106. Doesn't work as expected. @lymacasm  will continue investigating.

**Comment by batesandy123** [comment]
Repo for guy using a more up to date hardware version
https://github.com/clubcapra/microstrain_3dmgx1_imu

Datasheets for IMU
[IMU_datasheets.zip](https://github.com/uvic-auvic/polaris/files/2029388/IMU_datasheets.zip)

In sip file above is my code (python) and the old code on the submarine (java)
