### ISSUE TITLE
Create the Power board ros node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#55]
***MIGRATED FROM REDHERRING REPO***

Look at the motor_controller node and create something similar which is in charge of getting information out of the soft start. You can reuse the setupSerialConnection and serial_out functions. Place the node in the system_manager package

**Comment by asinha94** [comment]
Updated in #104. Skeleton is all there, just need to update. Prefereably by someone else

**Comment by lymacasm** [comment]
I can get it updated
