### ISSUE TITLE
Create an Edge detection ROS node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#56]
***MIGRATED FROM REDHERRING REPO***

This node should be able to recieve

ROS images via subsriber example
maybe transmit ROS images via publisher example
should only do processing if it is 'enabled' i.e a service call to enable/disable processing OR shutdown the subscriber itself (might need some testing)
send out a ROS msg of any object edge detected as well as the angle of the edge with reference to the edge of the image (frame)
Should be rosified and needs to be able to be run with a launchfile.

The node needs to use something like the sobel transform to compute the angle.

You will also need to modify the position msg to tell you what the angle of the object is

**Comment by asinha94** [comment]
moving from single-operation nodes to monolithic processing nodes
