### ISSUE TITLE
Create ROS colour detection Node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#57]
***MIGRATED FROM REDHERRING REPO***

his node should be able to recieve

ROS images via subsriber example
maybe transmit ROS images via publisher example
should only do processing if it is 'enabled' i.e a service call to enable/disable processing OR shutdown the subscriber itself (might need some testing)
send out a ROS msg of any object detected
Should be rosified and needs to be able to be run with a launchfile

**Comment by asinha94** [comment]
moving from single-operation nodes to monolithic processing nodes
