### ISSUE TITLE
Create the ROS classifier node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#58]
***MIGRATED FROM REDHERRING REPO***

This node should be able to recieve

ROS images via subsriber example
maybe transmit ROS images via publisher example
should only do processing if it is 'enabled' i.e a service call to enable/disable processing OR shutdown the subscriber itself (might need some testing)
send out a ROS msg of any object detected

**Comment by asinha94** [comment]
using TF now
