### ISSUE TITLE
Allow for Camera stream in the GUI to be dynamically adjusted

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#64]
***MIGRATED FROM REDHERRING REPO***

So we might want to change the video stream in some way, such as apply filters or maybe even change the subscriber topic entirely. So either the GUI needs to be modified so that it can modify its topic name at runtime, or the vision node, will change it's output. Most probably it will get sent to an intermediary node which will do the processing and send the image stream to the GUI

**Comment by batesandy123** [comment]
This should be closed @asinha94 . Let me know what you think

**Comment by asinha94** [comment]
Drop down box would be nice though
