### ISSUE TITLE
Create a script which converts blender files to collada (.dae)

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#65]
***MIGRATED FROM REDHERRING REPO***

So currently the only way to convert .blend files to collada is by opening it in blender, but that can take a while and is a bit annoying. Blender has some APIs we can use, specifically python APIs, so a simple conversion script would be nice.

**Comment by asinha94** [comment]
scrapping gazebo for the foreseeable future
