### ISSUE TITLE
Make sure all the Models in the Gazebo_Models repo work

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#70]
***MIGRATED FROM REDHERRING REPO***

Open them up in Blender to make sure they are actually there and also make sure you can import them into the mesh (.dae) into Gazebo

http://gazebosim.org/tutorials/?tut=import_mesh will come in handy

**Comment by asinha94** [comment]
scrapping gazebo for the foreseeable future
