### ISSUE TITLE
Add option to record video output in GUI

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#82]
***MIGRATED FROM REDHERRING REPO***

Click the button and it will automatically start recording to a filestamped named in ~/Documents/redherrring/videos/ (or something like that)

**Comment by asinha94** [comment]
Should be done with rosbags

**Comment by batesandy123** [comment]
This was not done in the gui, but a true/false option has been added to launch.launch

**Comment by asinha94** [comment]
closed in #107
