### ISSUE TITLE
Implement enableControls function in all of the other tabs

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#86]
***MIGRATED FROM REDHERRING REPO***

So Whenever the control button is toggled between ROV and AUV, it will enable/disable things as necessary, for example the joystick settings and lights etc... At the moment it only disables the things in the control tab. Implement this in all the other tabs.

Remember to update the enableControls function in MainWindow so that it is actually called whenever the signal is emitted.

While you're at it, inside all of the init functions all the boxes, buttons, fields etc... should be enables when the program first starts up. I.e for every element in the tab write ui->element_name->setEnabled(true).

**Comment by asinha94** [comment]
moving to web gui so trash this
