### ISSUE TITLE
Add logging feed to the GUI

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#89]
***MIGRATED FROM REDHERRING REPO***

So the GUI has a logging form which accepts a scrolling text stream, so we just need to configure the QNode.cpp file to continuously read the ROS logs and concat them to the log form

**Comment by asinha94** [comment]
Completeted by @bates-andy123. Pending pull request

**Comment by asinha94** [comment]
add in #103
