### ISSUE TITLE
Create the depth sensor ROS node

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#9]
This task entails:

-Writing a ROS depth sensor node
-Node must handle all cases
-Read in ascii control commands/returns to and from the depth snesor and info manager node
-Create a test case node to "fake" systems for input from depth sensor and info manager node and
test for correct function and output
-Node must return conformation to peripheral manager of performed action
-Node must perform needed math and return relevant information extracted

**Comment by asinha94** [comment]
depth sensor is now part of power board node.
